### ISSUE TITLE
数据能分享一下么

### ISSUE THREAD

**Issue by 93Alliance** [hcygeorge/aoi_defect_detection#2]
我想重现你的代码，但是苦于没有数据，您能分享一下么？

**Comment by hcygeorge** [comment]
抱歉，這個原始數據是由工研院提供，我並沒有數據的所有權，所以沒辦法公開分享。建議你可以改用其他開源的瑕疵數據，例如這個https://github.com/Charmve/Surface-Defect-Detection，當然程式碼也做相應修改。

**Comment by hcygeorge** [comment]
抱歉，這個原始數據是由工研院提供，我並沒有數據的所有權，所以沒辦法公開分享。建議你可以改用開源的瑕疵數據，例如[Surface-Defect-Detection](https://github.com/Charmve/Surface-Defect-Detection)

當然程式碼也要做相應修改，祝你好運。
